######################################################
#
# yaml配置说明
# 1 ： 说明：host：与192之间必须有空格，246：与3306不需要
#
#####################################################


#数据库配置
type: mysql
name: root
pwrd: 123456
host: 127.0.0.1
port: 3306
dbname: macmysql
charset: utf8
maxidle: 500
maxconn: 1000

